<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Schema;

/**
 * Regenerates the always-current wiki pages from the live code so they cannot drift:
 *   docs/features/index.md   — scenario counts per feature, from the Gherkin specs
 *   docs/reference/routes.md — the HTTP route table
 *   docs/reference/schema.md — every table and its columns
 *
 * These pages are marked "generated — do not edit"; edit the source instead.
 */
class DocsGenerate extends Command
{
    protected $signature = 'docs:generate';

    protected $description = 'Regenerate the generated wiki pages (feature status, routes, schema)';

    private const STAMP = "<!-- GENERATED by `php artisan docs:generate` — do not edit by hand. -->\n\n";

    public function handle(): int
    {
        $this->generateFeatures();
        $this->generateRoutes();
        $this->generateSchema();
        $this->info('Regenerated docs/features/index.md, docs/reference/routes.md, docs/reference/schema.md');

        return self::SUCCESS;
    }

    private function generateFeatures(): void
    {
        $dir = base_path('formynieces-spec/features');
        $rows = [];
        $total = 0;
        $mvp = 0;

        foreach (File::glob($dir.'/*.feature') ?: [] as $path) {
            $text = (string) File::get($path);
            $name = preg_match('/^Feature:\s*(.+)$/m', $text, $m) ? trim($m[1]) : basename($path, '.feature');
            $isMvp = str_contains(substr($text, 0, 200), '@mvp');
            $scenarios = preg_match_all('/^\s*Scenario(?: Outline)?:/m', $text);
            $rows[] = ['name' => $name, 'mvp' => $isMvp, 'scenarios' => $scenarios];
            $total += $scenarios;
            $mvp += $isMvp ? $scenarios : 0;
        }

        usort($rows, fn ($a, $b) => [$b['mvp'], $b['scenarios']] <=> [$a['mvp'], $a['scenarios']]);

        $out = self::STAMP."# Feature Status\n\n";
        $out .= 'Generated from `formynieces-spec/features/*.feature`. ';
        $out .= "**{$total} scenarios** across ".count($rows)." features ({$mvp} in MVP features). ";
        $out .= "For built/tested/verified detail run `php artisan specs:trace`.\n\n";
        $out .= "| Feature | Tier | Scenarios |\n|---|---|---:|\n";
        foreach ($rows as $r) {
            $tier = $r['mvp'] ? 'MVP' : 'roadmap';
            $out .= "| {$r['name']} | {$tier} | {$r['scenarios']} |\n";
        }

        File::ensureDirectoryExists(base_path('docs/features'));
        File::put(base_path('docs/features/index.md'), $out);
    }

    private function generateRoutes(): void
    {
        $out = self::STAMP."# HTTP Routes\n\n| Method | URI | Name |\n|---|---|---|\n";
        $routes = collect(Route::getRoutes())
            ->filter(fn ($r) => ! str_starts_with($r->uri(), '_') && $r->uri() !== 'up')
            ->sortBy(fn ($r) => $r->uri());

        foreach ($routes as $r) {
            $methods = implode(', ', array_diff($r->methods(), ['HEAD']));
            $name = $r->getName() ?: '';
            $out .= '| '.$methods.' | `/'.$r->uri().'` | '.$name." |\n";
        }

        File::ensureDirectoryExists(base_path('docs/reference'));
        File::put(base_path('docs/reference/routes.md'), $out);
    }

    private function generateSchema(): void
    {
        $out = self::STAMP."# Database Schema\n\n";
        $tables = collect(DB::select("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"))
            ->pluck('name');

        foreach ($tables as $table) {
            if (in_array($table, ['migrations', 'sessions', 'cache', 'cache_locks', 'jobs', 'job_batches', 'failed_jobs', 'password_reset_tokens'], true)) {
                continue;
            }
            $columns = Schema::getColumnListing($table);
            $out .= "### `{$table}`\n\n";
            $out .= '`'.implode('`, `', $columns)."`\n\n";
        }

        File::ensureDirectoryExists(base_path('docs/reference'));
        File::put(base_path('docs/reference/schema.md'), $out);
    }
}
