<x-layouts::guardian>
<style>.pp-wrap{max-width:900px}.pp-card{background:var(--paper-2);border:1px solid var(--line);border-radius:var(--radius);padding:20px;margin-bottom:16px;box-shadow:var(--shadow-sm)}.pp-btn{border:0;border-radius:11px;padding:10px 16px;background:var(--teal);color:#fff;font:800 14px Nunito;cursor:pointer}.pp-note{color:var(--ink-soft);line-height:1.55}.pp-q{display:grid;grid-template-columns:1fr 260px;gap:16px;padding:14px 0;border-bottom:1px solid var(--line)}.pp-q:last-child{border:0}.pp-q label{font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.07em;color:var(--ink-faint)}.pp-q input{width:100%;padding:10px;border:1px solid var(--line);border-radius:9px;font:600 14px Nunito}@media(max-width:650px){.pp-q{grid-template-columns:1fr}}</style>
<div class="pp-wrap"><p><a href="{{ route('guardian.past-papers.show', [$student,$sitting]) }}" style="color:var(--teal)">← Paper</a></p>
<div class="pp-card"><h1 style="font:600 28px Fredoka;margin:0">Review {{ $sitting->paper_code }}</h1><p class="pp-note">OCR suggestions are shown when available. Check every low-confidence answer before grading; your correction is the final word.</p>@if(session('upload_saved'))<p role="status"><strong>Pages saved.</strong> Confirm the answers below when ready.</p>@endif @if(session('rewrite_required'))<p role="alert" style="color:#b45309;font-weight:800">The handwriting could not be read reliably. Please have {{ $student->name }} rewrite the answers more clearly and upload the new pages before continuing.</p>@endif</div>
@if($sitting->submissions->last()?->digitisation_status === 'rewrite_required')
<div class="pp-card"><h2 style="font:600 21px Fredoka;margin:0 0 6px">Rewrite required</h2><p class="pp-note">Use darker writing, leave space between answers, and keep the whole question number in frame. The paper cannot be graded until a readable page is uploaded.</p><form method="POST" action="{{ route('guardian.past-papers.upload', [$student,$sitting]) }}" enctype="multipart/form-data">@csrf<input type="file" name="pages[]" multiple accept=".jpg,.jpeg,.png,.webp" required><button class="pp-btn" type="submit" style="margin-left:8px">Upload clearer pages →</button></form></div>
@else
<form method="POST" action="{{ route('guardian.past-papers.grade', [$student,$sitting]) }}" class="pp-card">@csrf @foreach($questions as $question) @php($existing=$sitting->answers->firstWhere('past_paper_question_id',$question->id))<div class="pp-q"><div><strong>{{ $question->number }}. {{ $question->prompt }}</strong><p class="pp-note">{{ implode(' · ', $question->options ?? []) }}</p>@if($existing && $existing->confidence < .70)<small style="color:#b45309;font-weight:800">Low confidence — please check</small>@endif</div><div><label for="answer-{{ $question->id }}">Answer</label><input id="answer-{{ $question->id }}" name="answers[{{ $question->id }}]" value="{{ old('answers.'.$question->id, $existing?->read_answer) }}" autocomplete="off"></div></div>@endforeach<button class="pp-btn" type="submit">Save and grade →</button></form>
@endif</div></x-layouts::guardian>
